-- =====================================================================
--  GKKK Kotaraja - skema + RLS untuk Supabase (Postgres)
--  Jalankan SEKALI di: Supabase Dashboard > SQL Editor > New query
--
--  PENTING: file ini butuh hak postgres (superuser). Jangan pernah
--  menaruh password postgres di kode frontend atau di repo ini.
--  Browser cukup memakai ANON KEY.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. TABEL
--    tanggal  -> DATE  (SQLite pakai TEXT + GLOB; Postgres punya tipe
--                asli jadi validasi & sorting jadi benar)
--    diubah   -> TIMESTAMPTZ (dulu TEXT default datetime('now'))
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.jadwal_komisi (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tanggal         date        NOT NULL,
  tipe            text        NOT NULL DEFAULT 'KOMISI' CHECK (tipe IN ('KU','KOMISI')),
  komisi          text        NOT NULL,
  jenis_ibadah    text        NOT NULL DEFAULT '',
  tuan_rumah      text        NOT NULL DEFAULT '',
  liturgis        text        NOT NULL DEFAULT '',
  pelayan_firman  text        NOT NULL DEFAULT '',
  judul           text        NOT NULL,
  teks            text        NOT NULL DEFAULT '',
  nats_pembimbing text        NOT NULL DEFAULT '',
  tujuan          text        NOT NULL DEFAULT '',
  tempat          text        NOT NULL DEFAULT '',
  waktu           text        NOT NULL DEFAULT '',
  status          text        NOT NULL DEFAULT 'TERJADWAL' CHECK (status IN ('TERJADWAL','SELESAI','BATAL')),
  diubah          timestamptz NOT NULL DEFAULT now(),
  -- Kunci alami. SQLite dulu tidak punya UNIQUE ini, jadi saveKomisi()
  -- mencocokkan (tanggal, komisi) manual sebelum insert/update
  -- (server.js:92-102). Di Postgres kita jadikan constraint supaya
  -- import CSV bisa memakai .upsert() dan tidak pernah dobel.
  CONSTRAINT uq_jk UNIQUE (tanggal, komisi)
);

CREATE TABLE IF NOT EXISTS public.mezbah (
  tanggal      date        PRIMARY KEY,
  judul        text        NOT NULL,
  tema         text        NOT NULL DEFAULT '',
  bacaan       text        NOT NULL DEFAULT '',
  ayat         text        NOT NULL DEFAULT '',
  renungan     text        NOT NULL,
  pesan        text        NOT NULL DEFAULT '',
  refleksi     text        NOT NULL DEFAULT '',
  doa_gkkk     text        NOT NULL DEFAULT '',
  doa_misi     text        NOT NULL DEFAULT '',
  doa_penutup  text        NOT NULL DEFAULT '',
  diubah       timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.berita (
  id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tanggal  date        NOT NULL,
  judul    text        NOT NULL,
  ringkasan text       NOT NULL DEFAULT '',
  gambar   text        NOT NULL DEFAULT '',
  isi      text        NOT NULL,
  diubah   timestamptz NOT NULL DEFAULT now()
);

-- idx_jk tidak dibuat lagi: UNIQUE (tanggal, komisi) di atas sudah
-- menghasilkan index dengan kolom & urutan yang sama, sehingga sekaligus
-- melayani query ORDER BY tanggal DESC, komisi.
CREATE INDEX IF NOT EXISTS idx_berita ON public.berita (tanggal DESC, id DESC);

-- ---------------------------------------------------------------------
-- 1b. BATAS PANJANG KOLOM
--     Dulu hanya dicek di server.js (KF/FIELDS/BF). Sekarang jadi CHECK
--     constraint di database, jadi tetap berlaku dari client mana pun -
--     bukan cuma dari form ini. Di-drop dulu biar file bisa dijalankan ulang.
-- ---------------------------------------------------------------------
ALTER TABLE public.jadwal_komisi DROP CONSTRAINT IF EXISTS c_komisi, DROP CONSTRAINT IF EXISTS c_jenis_ibadah, DROP CONSTRAINT IF EXISTS c_tuan_rumah, DROP CONSTRAINT IF EXISTS c_liturgis, DROP CONSTRAINT IF EXISTS c_pelayan_firman, DROP CONSTRAINT IF EXISTS c_judul, DROP CONSTRAINT IF EXISTS c_teks, DROP CONSTRAINT IF EXISTS c_nats, DROP CONSTRAINT IF EXISTS c_tujuan, DROP CONSTRAINT IF EXISTS c_tempat, DROP CONSTRAINT IF EXISTS c_waktu;
ALTER TABLE public.jadwal_komisi
  ADD CONSTRAINT c_komisi         CHECK (char_length(komisi)         <= 40),
  ADD CONSTRAINT c_jenis_ibadah   CHECK (char_length(jenis_ibadah)   <= 80),
  ADD CONSTRAINT c_tuan_rumah     CHECK (char_length(tuan_rumah)     <= 120),
  ADD CONSTRAINT c_liturgis       CHECK (char_length(liturgis)       <= 120),
  ADD CONSTRAINT c_pelayan_firman CHECK (char_length(pelayan_firman) <= 120),
  ADD CONSTRAINT c_judul          CHECK (char_length(judul)          <= 200),
  ADD CONSTRAINT c_teks           CHECK (char_length(teks)           <= 200),
  ADD CONSTRAINT c_nats           CHECK (char_length(nats_pembimbing)<= 200),
  ADD CONSTRAINT c_tujuan         CHECK (char_length(tujuan)         <= 3000),
  ADD CONSTRAINT c_tempat         CHECK (char_length(tempat)         <= 120),
  ADD CONSTRAINT c_waktu          CHECK (char_length(waktu)          <= 40);

ALTER TABLE public.mezbah DROP CONSTRAINT IF EXISTS c_m_judul, DROP CONSTRAINT IF EXISTS c_m_tema, DROP CONSTRAINT IF EXISTS c_m_bacaan, DROP CONSTRAINT IF EXISTS c_m_ayat, DROP CONSTRAINT IF EXISTS c_m_renungan, DROP CONSTRAINT IF EXISTS c_m_pesan, DROP CONSTRAINT IF EXISTS c_m_refleksi, DROP CONSTRAINT IF EXISTS c_m_doa_gkkk, DROP CONSTRAINT IF EXISTS c_m_doa_misi, DROP CONSTRAINT IF EXISTS c_m_doa_penutup;
ALTER TABLE public.mezbah
  ADD CONSTRAINT c_m_judul       CHECK (char_length(judul)      <= 200),
  ADD CONSTRAINT c_m_tema        CHECK (char_length(tema)       <= 200),
  ADD CONSTRAINT c_m_bacaan      CHECK (char_length(bacaan)     <= 200),
  ADD CONSTRAINT c_m_ayat        CHECK (char_length(ayat)       <= 200),
  ADD CONSTRAINT c_m_renungan    CHECK (char_length(renungan)   <= 10000),
  ADD CONSTRAINT c_m_pesan       CHECK (char_length(pesan)      <= 3000),
  ADD CONSTRAINT c_m_refleksi    CHECK (char_length(refleksi)   <= 3000),
  ADD CONSTRAINT c_m_doa_gkkk    CHECK (char_length(doa_gkkk)   <= 10000),
  ADD CONSTRAINT c_m_doa_misi    CHECK (char_length(doa_misi)   <= 5000),
  ADD CONSTRAINT c_m_doa_penutup CHECK (char_length(doa_penutup)<= 3000);

ALTER TABLE public.berita DROP CONSTRAINT IF EXISTS c_b_judul, DROP CONSTRAINT IF EXISTS c_b_ringkasan, DROP CONSTRAINT IF EXISTS c_b_isi, DROP CONSTRAINT IF EXISTS c_b_gambar;
ALTER TABLE public.berita
  ADD CONSTRAINT c_b_judul     CHECK (char_length(judul)     <= 200),
  ADD CONSTRAINT c_b_ringkasan CHECK (char_length(ringkasan) <= 600),
  ADD CONSTRAINT c_b_isi       CHECK (char_length(isi)       <= 20000),
  ADD CONSTRAINT c_b_gambar    CHECK (char_length(gambar)    <= 4000);

-- ---------------------------------------------------------------------
-- 2. ROW LEVEL SECURITY  (WAJIB - ini yang melindungi database)
--
--    Tanpa baris di bawah, ANON KEY (=kunci publik yang tertanam di
--    halaman web) bisa baca SELEUH database dan menulis bebas.
--    Role postgres selalu lewat RLS, tapi anon harus dibatasi policy.
--
--    anon         = pengunjung tanpa login  -> hanya boleh BACA
--    authenticated= admin yang sudah login -> boleh baca + tulis
-- ---------------------------------------------------------------------
ALTER TABLE public.jadwal_komisi ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mezbah        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.berita        ENABLE ROW LEVEL SECURITY;

--Policies dibuang dulu supaya file ini bisa dijalankan ulang tanpa error
DROP POLICY IF EXISTS "publik baca jadwal"  ON public.jadwal_komisi;
DROP POLICY IF EXISTS "publik baca mezbah"  ON public.mezbah;
DROP POLICY IF EXISTS "publik baca berita"  ON public.berita;
DROP POLICY IF EXISTS "admin tulis jadwal"  ON public.jadwal_komisi;
DROP POLICY IF EXISTS "admin tulis mezbah"  ON public.mezbah;
DROP POLICY IF EXISTS "admin tulis berita"  ON public.berita;

-- baca publik (jadwal, mezbah, berita) ----------------------------------
CREATE POLICY "publik baca jadwal" ON public.jadwal_komisi
  FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "publik baca mezbah" ON public.mezbah
  FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "publik baca berita" ON public.berita
  FOR SELECT TO anon, authenticated USING (true);

-- tulis admin (hanya user yang sudah login lewat Supabase Auth) ---------
CREATE POLICY "admin tulis jadwal" ON public.jadwal_komisi
  FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "admin tulis mezbah" ON public.mezbah
  FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "admin tulis berita" ON public.berita
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ---------------------------------------------------------------------
-- 2b. HAK AKSES ROLE  (GRANT)
--
--     Policy RLS menentukan "baris mana yang boleh terlihat", tapi GRANT
--     menentukan "boleh menyentuh tabel ini sama sekali atau tidak".
--     Dua hal terpisah: tanpa GRANT, PostgREST menjawab
--     'permission denied for table' dan policy di atas tidak pernah
--     dievaluasi -- gejalanya situs kosong tanpa error yang jelas.
--
--     Supabase umumnya sudah memberi default privilege, tapi kita tidak
--     mau bergantung pada itu. Ditulis eksplisit, dan sengaja tidak
--     memakai GRANT ALL supaya anon tidak dapat menulis.
-- ---------------------------------------------------------------------
GRANT USAGE ON SCHEMA public TO anon, authenticated;

GRANT SELECT                 ON public.jadwal_komisi TO anon, authenticated;
GRANT SELECT                 ON public.mezbah        TO anon, authenticated;
GRANT SELECT                 ON public.berita        TO anon, authenticated;

GRANT INSERT, UPDATE, DELETE ON public.jadwal_komisi TO authenticated;
GRANT INSERT, UPDATE, DELETE ON public.mezbah        TO authenticated;
GRANT INSERT, UPDATE, DELETE ON public.berita        TO authenticated;

-- id memakai GENERATED ... AS IDENTITY, jadi menulis butuh hak atas
-- sequence di belakangnya. Tanpa baris ini, INSERT jadwal/berita gagal
-- dengan 'permission denied for sequence'.
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

-- =====================================================================
--  3. DATA JEMAAT
--
--     Dua tabel, bukan satu, karena dua jenis tulisan yang berbeda:
--      jemaat        = daftar resmi. HANYA admin boleh baca dan tulis.
--      jemaat_daftar = pendaftaran dari form publik. Pengunjung boleh
--                    MENYISIPKAN, tapi tidak boleh membaca (nama, lahir,
--                    alamat, HP = data pribadi).
--     Kalau digabung jadi satu, pengunjung bisa menyisipkan baris langsung
--     ke daftar resmi dan membaca semua data pribadi lewat policy longgar.
-- =====================================================================
CREATE TABLE IF NOT EXISTS public.jemaat (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  no_keluarga   text        NOT NULL DEFAULT '',
  nama_keluarga text        NOT NULL DEFAULT '',
  nama          text        NOT NULL,
  kepala        text        NOT NULL DEFAULT '',
  jk            text        NOT NULL DEFAULT '' CHECK (jk IN ('L','P','')),
  lahir         date,
  daerah        text        NOT NULL DEFAULT '',
  komisi        text        NOT NULL DEFAULT '',
  alamat        text        NOT NULL DEFAULT '',
  hp            text        NOT NULL DEFAULT '',
  diubah        timestamptz NOT NULL DEFAULT now(),
  -- kunci alami: nomor keluarga + nama. Impor Excel memakai .upsert()
  -- sehingga baris yang sudah ada diperbarui, bukan digandakan.
  CONSTRAINT uq_jemaat UNIQUE (no_keluarga, nama)
);

-- Untuk database yang sudah pernah dibuat, jalankan ini sekali supaya kolom
-- komisi ikut tersedia. CREATE TABLE IF NOT EXISTS tidak menambah kolom baru.
ALTER TABLE public.jemaat ADD COLUMN IF NOT EXISTS komisi text NOT NULL DEFAULT '';
ALTER TABLE public.jemaat_daftar ADD COLUMN IF NOT EXISTS komisi text NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS public.jemaat_daftar (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_keluarga text        NOT NULL DEFAULT '',
  nama          text        NOT NULL,
  kepala        text        NOT NULL DEFAULT '',
  jk            text        NOT NULL DEFAULT '' CHECK (jk IN ('L','P','')),
  lahir         date,
  daerah        text        NOT NULL DEFAULT '',
  komisi        text        NOT NULL DEFAULT '',
  alamat        text        NOT NULL DEFAULT '',
  hp            text        NOT NULL DEFAULT '',
  dibuat        timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.jemaat        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jemaat_daftar ENABLE ROW LEVEL SECURITY;

-- jemaat_daftar ditulis langsung oleh pengunjung lewat API, jadi panjang
-- kolom harus dibatasi DI DATABASE. Validator di app.js tidak cukup: orang
-- bisa saja memanggil PostgREST langsung tanpa lewat halaman kita.
-- DROP CONSTRAINT dulu, sama seperti blok constraint di atas. Tanpa ini file
-- hanya bisa dijalankan sekali: "constraint already exists" menggagalkan
-- seluruh skrip, karena SQL Editor membungkusnya dalam satu transaksi.
ALTER TABLE public.jemaat_daftar
  DROP CONSTRAINT IF EXISTS c_jd_nama, DROP CONSTRAINT IF EXISTS c_jd_klg,
  DROP CONSTRAINT IF EXISTS c_jd_kep, DROP CONSTRAINT IF EXISTS c_jd_daerah,
  DROP CONSTRAINT IF EXISTS c_jd_komisi, DROP CONSTRAINT IF EXISTS c_jd_alamat,
  DROP CONSTRAINT IF EXISTS c_jd_hp;
ALTER TABLE public.jemaat_daftar
  ADD CONSTRAINT c_jd_nama   CHECK (char_length(nama)           BETWEEN 2 AND 120),
  ADD CONSTRAINT c_jd_klg    CHECK (char_length(nama_keluarga) <= 80),
  ADD CONSTRAINT c_jd_kep    CHECK (char_length(kepala)        <= 120),
  ADD CONSTRAINT c_jd_daerah CHECK (char_length(daerah)       <= 120),
  ADD CONSTRAINT c_jd_komisi CHECK (char_length(komisi)       <= 40),
  ADD CONSTRAINT c_jd_alamat CHECK (char_length(alamat)       <= 400),
  ADD CONSTRAINT c_jd_hp    CHECK (char_length(hp)           <= 40);

DROP POLICY IF EXISTS "admin manages jemaat"   ON public.jemaat;
DROP POLICY IF EXISTS "publik daftar"      ON public.jemaat_daftar;
DROP POLICY IF EXISTS "admin baca pending" ON public.jemaat_daftar;
DROP POLICY IF EXISTS "admin hapus pending" ON public.jemaat_daftar;

CREATE POLICY "admin manages jemaat" ON public.jemaat
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Form publik: INSERT saja. Tidak ada SELECT/UPDATE/DELETE untuk anon, jadi
-- pengunjung tidak bisa membaca data pribadi orang lain, tidak bisa
-- menyunting daftar resmi, dan tidak bisa mengosongkan tabel.
CREATE POLICY "publik daftar" ON public.jemaat_daftar
  FOR INSERT TO anon, authenticated WITH CHECK (char_length(nama) BETWEEN 2 AND 120);

CREATE POLICY "admin baca pending" ON public.jemaat_daftar
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "admin hapus pending" ON public.jemaat_daftar
  FOR DELETE TO authenticated USING (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.jemaat         TO authenticated;
GRANT INSERT                           ON public.jemaat_daftar TO anon, authenticated;
GRANT SELECT, DELETE                   ON public.jemaat_daftar TO authenticated;

CREATE INDEX IF NOT EXISTS idx_jemaat_nama ON public.jemaat (nama);
CREATE INDEX IF NOT EXISTS idx_jemaat_klg  ON public.jemaat (no_keluarga);

-- Sequence: PostgREST butuh hak USAGE untuk menjalankan nextval() pada
-- DEFAULT id, jadi policy saja tidak cukup. Grant ALL SEQUENCES di section 2b
-- dijalankan SEBELUM tabel ini ada, sehingga sequence-nya belum ikut tercover.
GRANT USAGE, SELECT ON SEQUENCE public.jemaat_id_seq, public.jemaat_daftar_id_seq TO authenticated;
GRANT USAGE         ON SEQUENCE public.jemaat_daftar_id_seq TO anon;

-- =====================================================================
--  3. KELUARGA SEBAGAI BEBERAPA ORANG
--
-- Data jemaat sudah satu baris per orang, dikelompokkan lewat
--  no_keluarga. Jadi tidak perlu tabel baru: satu keluarga = beberapa baris
--  yang berbagi no_keluarga. Yang kurang cuma penanda di tabel antrean, supaya
--  admin tahu baris-baris mana satu pengiriman, bukan daftar terpisah.
--  keluarga_ref diisi browser (acak per submit), bukan nomor resmi.
-- =====================================================================
ALTER TABLE public.jemaat_daftar
  ADD COLUMN IF NOT EXISTS keluarga_ref text NOT NULL DEFAULT '';

ALTER TABLE public.jemaat_daftar
  DROP CONSTRAINT IF EXISTS c_jd_ref;
ALTER TABLE public.jemaat_daftar
  ADD CONSTRAINT c_jd_ref CHECK (char_length(keluarga_ref) <= 40);

CREATE INDEX IF NOT EXISTS idx_jd_ref ON public.jemaat_daftar (keluarga_ref);

-- =====================================================================
--  4. STATISTIK PUBLIK (view, bukan tabel)
--
--  Halaman Tentang boleh menampilkan angka, bukan orang. View ini hanya
--  berisi hitungan, tidak pernah mengembalikan baris, jadi RLS di
--  public.jemaat tidak perlu dibuka untuk anon. View bawaan Postgres
--  berjalan dengan hak pembuatnya (postgres), jadi RLS dilewati - aman
--  HANYA selama isinya agregat. Jangan pernah menambah kolom nama,
--  alamat, atau nomor HP di sini.
--
--  Untuk menyembunyikan statistik dari publik: hapus GRANT di baris
--  bawah, lalu jangan panggil view dari app.js. Tidak perlu mengDrop
--  tabel apa pun.
-- =====================================================================
CREATE OR REPLACE VIEW public.jemaat_ringkasan AS
SELECT
  count(*)::int                                                          AS jiwa,
  count(DISTINCT NULLIF(no_keluarga, ''))::int                           AS keluarga,
  count(*) FILTER (WHERE jk = 'L')::int                                  AS laki,
  count(*) FILTER (WHERE jk = 'P')::int                                  AS perempuan,
  count(*) FILTER (WHERE lahir IS NOT NULL
                     AND date_part('year', age(current_date, lahir)) < 12)::int  AS anak,
  count(*) FILTER (WHERE lahir IS NOT NULL
                     AND date_part('year', age(current_date, lahir)) BETWEEN 13 AND 17)::int AS remaja,
  count(*) FILTER (WHERE lahir IS NOT NULL
                     AND date_part('year', age(current_date, lahir)) BETWEEN 18 AND 59)::int AS dewasa,
  count(*) FILTER (WHERE lahir IS NOT NULL
                     AND date_part('year', age(current_date, lahir)) >= 60)::int AS lansia
FROM public.jemaat;

GRANT SELECT ON public.jemaat_ringkasan TO anon, authenticated;

-- =====================================================================
--  10. Teks halaman Tentang: kalimat statis yang disunting admin di tempat
-- =====================================================================
-- Satu baris per kunci, bukan satu kolom per kartu. Menambah kalimat yang
-- bisa disunting cukup menambah atribut data-tek="..." di index.html: tidak
-- perlu kolom baru, tidak perlu GRANT baru, tidak perlu kode baru.
--
-- CREATE TABLE IF NOT EXISTS (bukan DROP+CREATE) supaya isi yang sudah
-- disunting admin tidak hilang kalau file ini dijalankan ulang.
CREATE TABLE IF NOT EXISTS public.teks_tentang (
  kunci  TEXT PRIMARY KEY CHECK (kunci ~ '^[a-z0-9_]{1,40}$'),
  isi    TEXT NOT NULL DEFAULT '' CHECK (char_length(isi) <= 800),
  diubah TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE public.teks_tentang ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "publik baca teks"   ON public.teks_tentang;
DROP POLICY IF EXISTS "admin manages teks" ON public.teks_tentang;

-- Pendatang boleh baca: halaman Tentang memang untuk semua orang, dan
-- isinya bukan data pribadi.
CREATE POLICY "publik baca teks" ON public.teks_tentang
  FOR SELECT TO anon, authenticated USING (true);

-- Tulis hanya admin. Policy ini hanya berlaku untuk role 'authenticated',
-- jadi PostgREST tanpa sesi login tidak punya izin sama sekali - inilah yang
-- membuat proteksi tetap ada walau penyerang tahu format request-nya.
CREATE POLICY "admin manages teks" ON public.teks_tentang
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

GRANT SELECT                         ON public.teks_tentang TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.teks_tentang TO authenticated;

-- CATATAN KEAMANAN: 'authenticated' di sini berarti "punya sesi Supabase
-- Auth", BUKAN "pengelola gereja". Setiap akun yang berhasil login bisa
-- menyunting teks ini - sama seperti tabel berita dan jadwal. Kalau suatu saat
-- web ini punya pendaftaran umum, ganti TO authenticated dengan
--   USING (auth.uid() = (SELECT id FROM admin_users LIMIT 1))
-- supaya hanya satu akun yang boleh menulis.

-- =====================================================================
--  11. Kolom pelayanan = kolom "Kerinduan Pelayanan" di file Excel
-- =====================================================================
-- Spreadsheet "DATA JEMAAT" punya kolom "Kerinduan Pelayanan" (Liturgos,
-- Usher, Singer, Musik, LCD, ...). Tanpa kolom ini data itu dibuang saat
-- impor. Ditambahkan ke KEDUA tabel karena form publik menulis ke
-- jemaat_daftar, lalu admin menyalinnya ke jemaat saat menerima pendaftaran.
--
-- ADD COLUMN IF NOT EXISTS (bukan DROP+CREATE) supaya isi yang sudah ada
-- tidak hilang kalau file ini dijalankan ulang.
ALTER TABLE public.jemaat
  ADD COLUMN IF NOT EXISTS pelayanan text NOT NULL DEFAULT '';
ALTER TABLE public.jemaat_daftar
  ADD COLUMN IF NOT EXISTS pelayanan text NOT NULL DEFAULT '';

-- Batas panjang tetap ditegakkan di database, karena pengunjung bisa
-- memanggil PostgREST langsung tanpa lewat halaman kita.
ALTER TABLE public.jemaat_daftar DROP CONSTRAINT IF EXISTS c_jd_pelayanan;
ALTER TABLE public.jemaat_daftar
  ADD CONSTRAINT c_jd_pelayanan CHECK (char_length(pelayanan) <= 120);

-- =====================================================================
--  LANGKAH SETELAH MENJALANKAN FILE INI:
--
--  1. Rotate password postgres  (sudah kamu paste di chat - WAJIB ganti)
--  2. Authentication > Users > Add user
--       -> Email + password untuk ADMIN kamu, centang "Auto Confirm User"
--       -> JANGAN pakai email fake; ini yang akan mengunci writes
--  3. Settings > API > salin Project URL + anon/publishable key
--       -> taruh di  root/supabase-config.js  lalu commit
--
--       File ini BOLEH ikut di-commit dan BOLEH terlihat publik. Kunci
--       anon/publishable memang dirancang untuk ada di dalam browser;
--       yang melindungi data adalah RLS di file ini, bukan kerahasiaan
--       kunci. Yang TIDAK boleh masuk repo: password postgres dan
--       service_role key.
-- =====================================================================
