-- =====================================================================
--  GKKK Kotaraja - skema + RLS untuk Supabase (Postgres)
--  Jalankan SEKALI di: Supabase Dashboard > SQL Editor > New query
--
--  PENTING: file ini butuh hak postgres (superuser). Jangan pernah
--  menaruh password postgres di kode frontend atau di repo ini.
--  Browser cukup memakai ANON KEY.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. TABEL
--    tanggal  -> DATE  (SQLite pakai TEXT + GLOB; Postgres punya tipe
--                asli jadi validasi & sorting jadi benar)
--    diubah   -> TIMESTAMPTZ (dulu TEXT default datetime('now'))
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.jadwal_komisi (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tanggal         date        NOT NULL,
  tipe            text        NOT NULL DEFAULT 'KOMISI' CHECK (tipe IN ('KU','KOMISI')),
  komisi          text        NOT NULL,
  jenis_ibadah    text        NOT NULL DEFAULT '',
  tuan_rumah      text        NOT NULL DEFAULT '',
  liturgis        text        NOT NULL DEFAULT '',
  pelayan_firman  text        NOT NULL DEFAULT '',
  judul           text        NOT NULL,
  teks            text        NOT NULL DEFAULT '',
  nats_pembimbing text        NOT NULL DEFAULT '',
  tujuan          text        NOT NULL DEFAULT '',
  tempat          text        NOT NULL DEFAULT '',
  waktu           text        NOT NULL DEFAULT '',
  status          text        NOT NULL DEFAULT 'TERJADWAL' CHECK (status IN ('TERJADWAL','SELESAI','BATAL')),
  diubah          timestamptz NOT NULL DEFAULT now(),
  -- Kunci alami. SQLite dulu tidak punya UNIQUE ini, jadi saveKomisi()
  -- mencocokkan (tanggal, komisi) manual sebelum insert/update
  -- (server.js:92-102). Di Postgres kita jadikan constraint supaya
  -- import CSV bisa memakai .upsert() dan tidak pernah dobel.
  CONSTRAINT uq_jk UNIQUE (tanggal, komisi)
);

CREATE TABLE IF NOT EXISTS public.mezbah (
  tanggal      date        PRIMARY KEY,
  judul        text        NOT NULL,
  tema         text        NOT NULL DEFAULT '',
  bacaan       text        NOT NULL DEFAULT '',
  ayat         text        NOT NULL DEFAULT '',
  renungan     text        NOT NULL,
  pesan        text        NOT NULL DEFAULT '',
  refleksi     text        NOT NULL DEFAULT '',
  doa_gkkk     text        NOT NULL DEFAULT '',
  doa_misi     text        NOT NULL DEFAULT '',
  doa_penutup  text        NOT NULL DEFAULT '',
  diubah       timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.berita (
  id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tanggal  date        NOT NULL,
  judul    text        NOT NULL,
  ringkasan text       NOT NULL DEFAULT '',
  gambar   text        NOT NULL DEFAULT '',
  isi      text        NOT NULL,
  diubah   timestamptz NOT NULL DEFAULT now()
);

-- idx_jk tidak dibuat lagi: UNIQUE (tanggal, komisi) di atas sudah
-- menghasilkan index dengan kolom & urutan yang sama, sehingga sekaligus
-- melayani query ORDER BY tanggal DESC, komisi.
CREATE INDEX IF NOT EXISTS idx_berita ON public.berita (tanggal DESC, id DESC);

-- ---------------------------------------------------------------------
-- 1b. BATAS PANJANG KOLOM
--     Dulu hanya dicek di server.js (KF/FIELDS/BF). Sekarang jadi CHECK
--     constraint di database, jadi tetap berlaku dari client mana pun -
--     bukan cuma dari form ini. Di-drop dulu biar file bisa dijalankan ulang.
-- ---------------------------------------------------------------------
ALTER TABLE public.jadwal_komisi DROP CONSTRAINT IF EXISTS c_komisi, DROP CONSTRAINT IF EXISTS c_jenis_ibadah, DROP CONSTRAINT IF EXISTS c_tuan_rumah, DROP CONSTRAINT IF EXISTS c_liturgis, DROP CONSTRAINT IF EXISTS c_pelayan_firman, DROP CONSTRAINT IF EXISTS c_judul, DROP CONSTRAINT IF EXISTS c_teks, DROP CONSTRAINT IF EXISTS c_nats, DROP CONSTRAINT IF EXISTS c_tujuan, DROP CONSTRAINT IF EXISTS c_tempat, DROP CONSTRAINT IF EXISTS c_waktu;
ALTER TABLE public.jadwal_komisi
  ADD CONSTRAINT c_komisi         CHECK (char_length(komisi)         <= 40),
  ADD CONSTRAINT c_jenis_ibadah   CHECK (char_length(jenis_ibadah)   <= 80),
  ADD CONSTRAINT c_tuan_rumah     CHECK (char_length(tuan_rumah)     <= 120),
  ADD CONSTRAINT c_liturgis       CHECK (char_length(liturgis)       <= 120),
  ADD CONSTRAINT c_pelayan_firman CHECK (char_length(pelayan_firman) <= 120),
  ADD CONSTRAINT c_judul          CHECK (char_length(judul)          <= 200),
  ADD CONSTRAINT c_teks           CHECK (char_length(teks)           <= 200),
  ADD CONSTRAINT c_nats           CHECK (char_length(nats_pembimbing)<= 200),
  ADD CONSTRAINT c_tujuan         CHECK (char_length(tujuan)         <= 3000),
  ADD CONSTRAINT c_tempat         CHECK (char_length(tempat)         <= 120),
  ADD CONSTRAINT c_waktu          CHECK (char_length(waktu)          <= 40);

ALTER TABLE public.mezbah DROP CONSTRAINT IF EXISTS c_m_judul, DROP CONSTRAINT IF EXISTS c_m_tema, DROP CONSTRAINT IF EXISTS c_m_bacaan, DROP CONSTRAINT IF EXISTS c_m_ayat, DROP CONSTRAINT IF EXISTS c_m_renungan, DROP CONSTRAINT IF EXISTS c_m_pesan, DROP CONSTRAINT IF EXISTS c_m_refleksi, DROP CONSTRAINT IF EXISTS c_m_doa_gkkk, DROP CONSTRAINT IF EXISTS c_m_doa_misi, DROP CONSTRAINT IF EXISTS c_m_doa_penutup;
ALTER TABLE public.mezbah
  ADD CONSTRAINT c_m_judul       CHECK (char_length(judul)      <= 200),
  ADD CONSTRAINT c_m_tema        CHECK (char_length(tema)       <= 200),
  ADD CONSTRAINT c_m_bacaan      CHECK (char_length(bacaan)     <= 200),
  ADD CONSTRAINT c_m_ayat        CHECK (char_length(ayat)       <= 200),
  ADD CONSTRAINT c_m_renungan    CHECK (char_length(renungan)   <= 10000),
  ADD CONSTRAINT c_m_pesan       CHECK (char_length(pesan)      <= 3000),
  ADD CONSTRAINT c_m_refleksi    CHECK (char_length(refleksi)   <= 3000),
  ADD CONSTRAINT c_m_doa_gkkk    CHECK (char_length(doa_gkkk)   <= 10000),
  ADD CONSTRAINT c_m_doa_misi    CHECK (char_length(doa_misi)   <= 5000),
  ADD CONSTRAINT c_m_doa_penutup CHECK (char_length(doa_penutup)<= 3000);

ALTER TABLE public.berita DROP CONSTRAINT IF EXISTS c_b_judul, DROP CONSTRAINT IF EXISTS c_b_ringkasan, DROP CONSTRAINT IF EXISTS c_b_isi, DROP CONSTRAINT IF EXISTS c_b_gambar;
ALTER TABLE public.berita
  ADD CONSTRAINT c_b_judul     CHECK (char_length(judul)     <= 200),
  ADD CONSTRAINT c_b_ringkasan CHECK (char_length(ringkasan) <= 600),
  ADD CONSTRAINT c_b_isi       CHECK (char_length(isi)       <= 20000),
  ADD CONSTRAINT c_b_gambar    CHECK (char_length(gambar)    <= 4000);

-- ---------------------------------------------------------------------
-- 2. ROW LEVEL SECURITY  (WAJIB - ini yang melindungi database)
--
--    Tanpa baris di bawah, ANON KEY (=kunci publik yang tertanam di
--    halaman web) bisa baca SELEUH database dan menulis bebas.
--    Role postgres selalu lewat RLS, tapi anon harus dibatasi policy.
--
--    anon         = pengunjung tanpa login  -> hanya boleh BACA
--    authenticated= admin yang sudah login -> boleh baca + tulis
-- ---------------------------------------------------------------------
ALTER TABLE public.jadwal_komisi ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mezbah        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.berita        ENABLE ROW LEVEL SECURITY;

--Policies dibuang dulu supaya file ini bisa dijalankan ulang tanpa error
DROP POLICY IF EXISTS "publik baca jadwal"  ON public.jadwal_komisi;
DROP POLICY IF EXISTS "publik baca mezbah"  ON public.mezbah;
DROP POLICY IF EXISTS "publik baca berita"  ON public.berita;
DROP POLICY IF EXISTS "admin tulis jadwal"  ON public.jadwal_komisi;
DROP POLICY IF EXISTS "admin tulis mezbah"  ON public.mezbah;
DROP POLICY IF EXISTS "admin tulis berita"  ON public.berita;

-- baca publik (jadwal, mezbah, berita) ----------------------------------
CREATE POLICY "publik baca jadwal" ON public.jadwal_komisi
  FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "publik baca mezbah" ON public.mezbah
  FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "publik baca berita" ON public.berita
  FOR SELECT TO anon, authenticated USING (true);

-- tulis admin (hanya user yang sudah login lewat Supabase Auth) ---------
CREATE POLICY "admin tulis jadwal" ON public.jadwal_komisi
  FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "admin tulis mezbah" ON public.mezbah
  FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "admin tulis berita" ON public.berita
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ---------------------------------------------------------------------
-- 2b. HAK AKSES ROLE  (GRANT)
--
--     Policy RLS menentukan "baris mana yang boleh terlihat", tapi GRANT
--     menentukan "boleh menyentuh tabel ini sama sekali atau tidak".
--     Dua hal terpisah: tanpa GRANT, PostgREST menjawab
--     'permission denied for table' dan policy di atas tidak pernah
--     dievaluasi -- gejalanya situs kosong tanpa error yang jelas.
--
--     Supabase umumnya sudah memberi default privilege, tapi kita tidak
--     mau bergantung pada itu. Ditulis eksplisit, dan sengaja tidak
--     memakai GRANT ALL supaya anon tidak dapat menulis.
-- ---------------------------------------------------------------------
GRANT USAGE ON SCHEMA public TO anon, authenticated;

GRANT SELECT                 ON public.jadwal_komisi TO anon, authenticated;
GRANT SELECT                 ON public.mezbah        TO anon, authenticated;
GRANT SELECT                 ON public.berita        TO anon, authenticated;

GRANT INSERT, UPDATE, DELETE ON public.jadwal_komisi TO authenticated;
GRANT INSERT, UPDATE, DELETE ON public.mezbah        TO authenticated;
GRANT INSERT, UPDATE, DELETE ON public.berita        TO authenticated;

-- id memakai GENERATED ... AS IDENTITY, jadi menulis butuh hak atas
-- sequence di belakangnya. Tanpa baris ini, INSERT jadwal/berita gagal
-- dengan 'permission denied for sequence'.
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

-- =====================================================================
--  LANGKAH SETELAH MENJALANKAN FILE INI:
--
--  1. Rotate password postgres  (sudah kamu paste di chat - WAJIB ganti)
--  2. Authentication > Users > Add user
--       -> Email + password untuk ADMIN kamu, centang "Auto Confirm User"
--       -> JANGAN pakai email fake; ini yang akan mengunci writes
--  3. Settings > API > salin Project URL + anon/publishable key
--       -> taruh di  root/supabase-config.js  lalu commit
--
--       File ini BOLEH ikut di-commit dan BOLEH terlihat publik. Kunci
--       anon/publishable memang dirancang untuk ada di dalam browser;
--       yang melindungi data adalah RLS di file ini, bukan kerahasiaan
--       kunci. Yang TIDAK boleh masuk repo: password postgres dan
--       service_role key.
-- =====================================================================